ChainSafe/js-libp2p-noise

src/xx.ts
test/xx.test.ts

xx symmetric encryption

---

src/crypto.ts
src/encoder.ts
test/noise.test.ts
test/utils.ts

Fix sending payloads larger than 65,519 bytes

---

src/@types/handshake.ts
src/encoder.ts
src/handshake.ts
src/handshakes/abstract-handshake.ts
src/handshakes/ik.ts
src/handshakes/xx.ts
src/noise.ts
src/utils.ts
test/handshakes/ik.test.ts
test/handshakes/xx.test.ts
test/noise.test.ts

- moved common functions to separate abstract class
- ported IK handshake 
Note: I think better file naming should be made... :dagger:

IK handshake

---

src/handshake.ts
src/handshakes/xx.ts
src/noise.ts
src/utils.ts
test/handshake.test.ts
test/handshakes/ik.test.ts
test/handshakes/xx.test.ts
test/index.test.ts
test/noise.test.ts
test/utils.ts

Fix providing private key

---

package.json
src/encoder.ts
src/errors.ts
src/handshake-ik.ts
src/handshake-xx-fallback.ts
src/handshake-xx.ts
src/handshakes/ik.ts
src/keycache.ts
src/noise.ts
src/utils.ts
test/ik-handshake.test.ts
test/noise.test.ts
yarn.lock

Integrate IK handshake flow

---

.travis.yml

Run tests in CI

---

src/noise.ts
test/handshakes/ik.test.ts
test/handshakes/xx.test.ts
test/ik-handshake.test.ts
test/noise.test.ts
test/xx-fallback-handshake.test.ts
test/xx-handshake.test.ts

Set prologue to empty buffer

---

protos/payload.proto
src/utils.ts

- Conform with the latest spec update: https://github.com/libp2p/specs/pull/244/files

Update payload fields to latest spec

---

.travis.yml
karma.conf.js
package.json
protos/payload.proto
src/proto/payload.json
src/utils.ts
test/handshakes/ik.test.ts
test/handshakes/xx.test.ts
tsconfig.json
webpack.config.js
yarn.lock

- switch .proto with json definitions
- fix protobufsjs using Uint8Array instead of buffer on web
- add web test runner
resolves #22

Browser tests

---

CHANGELOG.md
package.json

Release 1.1.2

---

package.json
src/noise.ts
src/utils.ts
yarn.lock

Updating dependencies per https://github.com/ipfs/js-ipfs/issues/3504
eslint also updated per https://github.com/ipfs/aegir/pull/638

chore: update deps

---

CHANGELOG.md
package.json
yarn.lock

Urgent release to make libp2p-noise usable again

Release 2.0.4

---

.github/CODEOWNERS
.github/workflows/ci.yml
README.md
package.json

@GregTheGreek could you set NPM_AUTH_TOKEN secret as I don't have any rights in this repo?

Update to chainsafe

---

.github/workflows/ci.yml

It was removed to allow first deployment

revert ci fix

---

package.json

Seems like it ended up in dev deps and it's failing dep-check.

chore: add libp2p/crypto to prod dep

---

README.md

- now matches engine requirement in package.json

chore: update node.js badge version in readme

---

package.json

Update deps to latest versions with multiformats@11.
Supersedes #258, #259 and #260

chore: update @libp2p/daemon and interop tests

---

package.json

fix: add missing index.min.js to release files

---

package.json

Update `as-sha256` dependency to SIMD aware version

fix: update as-sha256

---

package.json

Seems to be causing publishing to fail.

fix: remove provenance
