ChainSafe/js-libp2p-noise

src/@types/handshake-interface.ts, src/@types/handshake.ts, src/handshake-ik.ts, src/handshake-xx-fallback.ts, src/handshake-xx.ts, src/keycache.ts, src/noise.ts, src/utils.ts, test/ik-handshake.test.ts, test/noise.test.ts, test/xx-fallback-handshake.test.ts
This is alternative to #31 
- remote peer is deducted from payload in message respective to the handshake type
- ik is tried if 
- initiator + noise pipes + has remote static key
- responder + noise pipes
Some tests are failing:
- 2 are wrong as they assume you will receive remote peer on inbound connection
- rest are failing because "Ephemeral keys doesn't exists"
=> Fix IK flow

package.json, src/@types/handshake-interface.ts, src/crypto.ts, src/handshake-ik.ts, src/handshake-xx-fallback.ts, src/handshake-xx.ts, src/handshakes/abstract-handshake.ts, src/handshakes/ik.ts, src/handshakes/xx.ts, test/handshakes/xx.test.ts, test/ik-handshake.test.ts, test/noise.test.ts, test/xx-handshake.test.ts, yarn.lock
- added check of aead decryption
- propagate valid flag (code more similar to go
- disabled "IK -> XX fallback: responder has disabled noise pipes", it didn't work before but now we detected invalid decryption
=> Verify aead decryption

src/encoder.ts, src/handshake-xx.ts, test/noise.test.ts
This branch makes the final message in the XX sequence conform to the Noise framework spec by removing the empty ephemeral key, as described in https://github.com/libp2p/go-libp2p-noise/issues/54.
I've merged in the fix on the go side, so now interop tests are failing against master. I have tested the new Go master branch against this js branch though, and it works.
Thanks again @sinkingsugar for filing the issue!
=> remove empty ephemeral key from XX message C

README.md, src/noise.ts, test/noise.test.ts
ref: https://github.com/libp2p/specs/issues/249
=> Disable noise pipes

package.json, src/@types/basic.ts, src/handshakes/abstract-handshake.ts, src/handshakes/ik.ts, src/handshakes/xx.ts, src/noise.ts, src/utils.ts, test/noise.test.ts, test/utils.ts, webpack.bundle.config.js, yarn.lock
Removes bcrypto from dependencies.
Replaced with: 
- [futoin-hdkf](https://www.npmjs.com/package/futoin-hkdf)
- [aead-js](https://www.npmjs.com/package/aead-js)
- [tweetnacl](https://www.npmjs.com/package/tweetnacl)
Related to issue: #27 
cc: @mpetrunic
=> Replace bcrypto with standalone libraries

src/@types/handshake-interface.ts, src/@types/libp2p.ts, src/handshake-ik.ts, src/handshake-xx-fallback.ts, src/handshake-xx.ts, src/noise.ts, test/noise.test.ts
Set remote early data when remote peer payload is verified and return from secureOutbound and secureInbound.
Related to issue: #53
=> Early data api

src/utils.ts
Currently in outbound xx handshakes we don't ensure the remotePeer contains a public key. To correct this I updated `verifySignedPayload` to create the key from the validated public key. While this is redundant for inline keys, it's necessary for rsa keys.
The remotePeer is already being assigned to the result of `verifySignedPayload`. In order for tests to catch this it would require a test with RSA keys instead of ed25519. Happy to add those tests if desired.
Resolves: https://github.com/NodeFactoryIo/js-libp2p-noise/issues/58
=> fix: marshal the verified peer from its public key

package.json
The [page for this module on npm](https://www.npmjs.com/package/libp2p-noise) doesn't have a link to the repo, I guess because it's specified as an ssh-type URL in the package.json file so npm can't turn it into a hyperlink.
The change here is to use a `git+https` URL which should let npm display a link on the module page.
=> chore: use http link for github repo

.aegir.js, package.json, src/proto/payload.d.ts, src/proto/payload.js, yarn.lock
- Updates all deps to pull in the latest buffer and bl modules
- Specifies a root name for pbjs code gen - message names for pbjs
generated code are global so specifying a root name scopes them
to prevent two modules accidentally trampling over each other's
protobuf code by giving their messages the same name
Refs: https://github.com/ipfs/js-ipfs-bitswap/pull/323
BREAKING CHANGE: buffer@6 dropped support for IE and Safari < 10
=> chore: update deps and specify root for pbjs

.github/workflows/ci.yml, .gitignore, package.json, src/handshakes/abstract-handshake.ts, src/noise.ts, src/utils.ts, yarn.lock
Replaced:
- bcrypto/x25519 with  https://github.com/StableLib/stablelib/tree/master/packages/x25519
- bcrypto/aead with https://github.com/StableLib/stablelib/tree/master/packages/chacha20poly1305
- bcrypto/hkdf with https://github.com/StableLib/stablelib/tree/master/packages/hkdf
resolves #93
=> Remove bcypto

package.json, yarn.lock
There's a new release of the `peer-id` module that uses the `CID` class from the `multiformats` module instead of from `cids`.
This PR upgrades to the new version (also upgrades mocha and sinon too).
BREAKING CHANGE: the new `peer-id` module uses the new `CID` class and not the old one
=> chore: update peer-id dep

package.json, src/utils.ts
It's only used to verify incoming message payloads but the `pubKey` property on `PeerId` can do that.
=> chore: make libp2p-crypto a dev dep

.github/workflows/ci.yml, .github/workflows/publish.yml, package.json, yarn.lock
Updates to the latest peer-id and libp2p-crypto.
No API changes, but libp2p-crypto removes some deps now that support for RSA in node core is better, though you need a modern node to use it.
BREAKING CHANGE: requires node 15+
=> chore: update peer-id and libp2p-crypto

src/@types/basic.d.ts, src/@types/handshake.d.ts, src/handshakes/abstract-handshake.ts
Resolves #102 
- Remove references to "uint32", which isn't in the spec and was misleading
- Check for a "max nonce" (`Number.MAX_SAFE_INTEGER`) when encrypting/decrypting
- Add comments describing the deviation from the spec, why it exists, and its effect
=> fix: safely handle nonces as 64 bit uints

src/handshakes/abstract-handshake.ts
The `value` and `offset` args to `Buffer.writeUInt32LE` vs `DataView.setUint32` are the other way round.
Fixes a bug introduced in #125 where we were using the nonce value as an offset and writing `4` rather than writing the nonce value at offset `4`.
=> fix: write handshake nonce correctly

src/constants.ts
To allow use of noise in the browser with minimal bundling, access `process.env.FOO` via `globalThis` and with optional chaining.
Removes the need to use babel etc to transpile the code first.
=> fix: access node process object via globalThis

README.md, src/@types/handshake-interface.ts, src/@types/libp2p.ts, src/crypto.ts, src/crypto/stablelib.ts, src/crypto/streaming.ts, src/encoder.ts, src/handshake-ik.ts, src/handshake-xx-fallback.ts, src/handshake-xx.ts, src/handshakes/abstract-handshake.ts, src/handshakes/ik.ts, src/handshakes/xx.ts, src/index.ts, src/keycache.ts, src/logger.ts, src/noise.ts, src/utils.ts, test/handshakes/ik.spec.ts, test/handshakes/xx.spec.ts, test/ik-handshake.spec.ts, test/keycache.spec.ts, test/noise.spec.ts, test/utils.ts, test/xx-fallback-handshake.spec.ts, test/xx-handshake.spec.ts
Hello.
This PR extracts all low level crypto interface in a specific file and makes the crypto interface pluggable in `Noise`.
Hope this helps!
=> feat: Make crypto implementation pluggable.

benchmarks/nonce.js, src/@types/handshake.ts, src/@types/nonce.ts, src/handshakes/abstract-handshake.ts, src/logger.ts, src/nonce.ts
**Motivation**
- There's a performance issue of `nonceToBytes()` as shown in https://github.com/ChainSafe/lodestar/issues/4140#issuecomment-1161174710
- Maintaining both Uint8Array and DataView and uint64 help improving nonce significantly
**Description**
- New `Nonce` class containing above data with `getUint64()`, `getBytes()` and `increase()` method
- New benchmark shows it's 150x faster
=> fix: improve nonce performance

src/handshake-ik.ts, src/handshake-xx-fallback.ts, src/handshake-xx.ts, src/handshakes/ik.ts, src/handshakes/xx.ts, src/utils.ts
- decodePayload is synchronous
- remove isValidPeerId - only decode peer id once
- don't use the return value of verifySignedPayload anywhere
- remove duplicate length check, use isValidPublicKey
=> chore: clean up logic

src/crypto/streaming.ts
**Motivation**
- `it-length-prefixed` 8.0.2 is a breaking change, it always yields `Uint8ArrayList`
**Description**
- Use that type
=> fix: correct type of it-length-prefixed 8.0.2

package.json, test/noise.spec.ts
The latest crypto release removed the ability to generate random data larger than 64kb so use iso-random-stream directly instead.
=> chore: fix tests

README.md, src/index.ts
In Cloudflare workers you cannot call some crypto functions outside of a request:
```
Error: Some functionality, such as asynchronous I/O (fetch, Cache API, KV), timeouts (setTimeout, setInterval), and generating random values (crypto.getRandomValues, crypto.subtle.generateKey), can only be performed while handling a request.
```
This error occurs when importing the module because a default instance is created up front (the `NOISE` export).
This PR removes the default `NOISE` export to allow folks to create an instance when needed.
BREAKING CHANGE: The default instance `NOISE` is not longer created or exported. Import `Noise` and use `new Noise()` in place of `NOISE`.
resolves https://github.com/ChainSafe/js-libp2p-noise/issues/180
=> feat!: remove default instance

package.json, src/noise.ts, src/proto/payload.ts
BREAKING CHANGE: secureInbound and secureOutbound now accept Duplex instead of any
=> chore!: update protons and connection encryption interface

src/handshakes/abstract-handshake.ts
resolves https://github.com/ChainSafe/js-libp2p-noise/issues/199
minimal fix
A bigger code change would involve `throw`ing at a lower level rather than pass `valid` boolean up (only to ultimately `throw` there)
=> fix: only increment nonce in valid decrypted msg

src/index.ts
So we can use the types in listeners for interested transports like WebTransport.
=> fix: add noise extension to return type

src/crypto/streaming.ts, src/encoder.ts, src/noise.ts
Javascript abstractions are not free. While using pipe here looks nice, it adds a non-neglible cost allocating Promises for each extra `for await ()` iteration.
- Similar rationale to https://github.com/libp2p/js-libp2p/issues/1420#issuecomment-1273272662
Move code to add prefix into encryptStream. I'll attempt the same for decryptStream but it's a bit more complex so prefer to split in two PRs
=> chore: Add prefix in encryptStream

package.json, src/crypto/streaming.ts, src/metrics.ts, src/noise.ts, test/index.spec.ts
Same as #224 but uses libp2p metrics interfaces
=> feat: add metrics

src/@types/handshake-interface.ts, src/crypto.ts, src/crypto/stablelib.ts, src/crypto/streaming.ts, src/handshake-xx.ts, src/handshakes/abstract-handshake.ts
**Motivation**
As tested in lodestar, memory allocation is expensive for `decrypt()` flow
**Description**
- Stablelib already supports option `dst?: Uint8Array` parameter in its chacha20poly1305 implementation, the new `as-chacha20poly1305` should follow the same interface
- When decrypting, reuse the same memory as encrypted message is not used after that
=> feat: reuse encrypted data to avoid memory allocation

README.md, test/index.spec.ts
=> fix: readme usage example

.github/dependabot.yml
The Semantic PR action requires the PR title prefix to be `chore:`, `fix:`, `feat:` or `docs:` but the dependabot config has it opening PRs with `dev:` as the title so update the config to have it open PRs with titles that pass the Semantic PR action.
=> chore: fix dependabot pr titles

src/utils.ts, test/xx-handshake.spec.ts
- Provide more context to debug mismatch instances like https://github.com/ChainSafe/lodestar/issues/4355
=> chore: Add peer id str to mismatch error

src/handshake-xx.ts, src/handshakes/abstract-handshake.ts
Noise logs in-progress business-as-usual style messages which can make the logs quite noisy.
This PR switches to using trace logging for those messages, you can see them if you include `*:trace` or similar in the debug string.
=> fix: use trace logging

package.json
Add types to exports in packages.json，to avoid not being able to locate the type definition file when using exports.
=> fix: add types to exports in packages.json

src/nonce.ts
The missing file extension breaks the package for consumers using `node16` module resolution with the following error:
```
node_modules/@chainsafe/libp2p-noise/dist/src/nonce.d.ts:1:36 - error TS2835: Relative import paths need explicit file extensions in EcmaScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean './@types/basic.js'?
```
These errors are easy to miss when using `node` module resolution in the library. I can set up another PR to update the module resolution to `node16` so these are easier to catch, if that's ok.
=> fix: add missing file extension in import

src/crypto/streaming.ts
Sending lots of tiny buffers kills TCP performance, even with `noDelay` disabled.
Sending the encrypted data length along with the data in one buffer increases `@libp2p/perf` throughput with noise+yamux from 300-320 MB/s to 320-340 MB/s
Flame graphs showing `Socket._writeGeneric` (e.g. writing to the TCP socket) while running the performance test:
Before:
After:
=> fix: concatenate encrypted data length prefix with data before sending

package.json, src/crypto/index.ts, src/encoder.ts, src/handshake-xx.ts, src/handshakes/abstract-handshake.ts, src/handshakes/xx.ts, src/noise.ts, src/nonce.ts, src/proto/payload.ts, test/xx-handshake.spec.ts
Using node crypto to do X25519 key operations instead of `@noble/curves` yields a nice little performance bump which translates to ever so slightly lower latencies when opening connections.
Running the `./benchmarks/benchmark.js` file shows a 2x improvement:
Before:
```console
% node ./benchmark.js
Initializing handshake benchmark
Init complete, running benchmark
handshake x 124 ops/sec ±0.47% (84 runs sampled)
```
After:
```console
% node ./benchmark.js
Initializing handshake benchmark
Init complete, running benchmark
handshake x 314 ops/sec ±0.99% (87 runs sampled)
```
Flamegraphs (same scale)
Before:
After:
=> fix: use node.js crypto for x25519 keys

src/crypto/index.browser.ts
This package is a dependency for https://github.com/waku-org/js-waku
But, due to the import on 'src/crypto/index.browser.ts' - `import { pureJsCrypto } from './.js'`, the CRA does not work. Fixed this by modifying the import
**Steps to reproduce**
1. Create a react app with `npx create-react-app <project-name>`
2. Install the waku sdk package from `npm install @waku/sdk`
3. Package installation fails and throws up the error because of the invalid import
This is a major issue because CRA will not along with package
=> fix: missing import extension

package.json
React-native doesn't have any node core modules so it must use the pure-js/browser implementations of everything.
=> feat: react-native support

package.json
It turns out this isn't necessary so revert the changes.
Also, we don't depend on node's `util` so no need to override that in the browser field.
=> fix: revert react-native changes in #403

package.json, src/noise.ts
The latest libp2p release allows services to declare their capabilities (what they provide to the node) and their dependencies (the capabilities they require other services to provide for the config to be "valid").
Adds the `serviceCapabilities` symbol property that says Noise provides the `@libp2p/connection-encryption` capability and also that it provides noise encryption as some transports (WebTransport, WebRTC) now require this module to be configured alongside them.
=> feat: add service capabilities definition

src/index.ts, src/noise.ts, test/compliance.spec.ts, test/index.spec.ts, test/noise.spec.ts
`libp2p@2.x.x` will remove the `localPeer` argument from the `secureInbound` and `secureOutbound` methods of the `ConnectionEncrypter` interface - see https://github.com/libp2p/js-libp2p/pull/2304.
Unfortunately the `js-libp2p` monorepo has a depdendency on this module so the change cannot be released until this module is compatible... with the unreleased change.
This PR tests the first argument to `secureInbound` and `secureOutbound` to ensure that it is actually a `PeerId`. If not it shuffles all the arguments along by one place.  This makes `@chainsafe/libp2p-noise` compatible with both `libp2p@1.x.x` and `libp2p@2.x.x`.
This PR can be reverted and the first argument removed once `libp2p@2.x.x` is released.
=> fix: make local peer id optional

package-lock.json, package.json, src/index.ts, src/noise.ts, src/proto/payload.proto, src/proto/payload.ts, src/types.ts, test/compliance.spec.ts, test/index.spec.ts, test/noise.spec.ts
Implements early multiplexer negotiation to save multistream-select round trips when a connection is opened.
Spec: https://github.com/libp2p/specs/blob/6d38f88f7b2d16b0e4489298bcd0737a6d704f7e/connections/inlined-muxer-negotiation.md#multiplexer-negotiation-over-noise
=> feat: select early muxer

package-lock.json, package.json, src/noise.ts, test/muxers.spec.ts, test/noise.spec.ts
Allows transports such as WebRTC-Direct to skip the early muxer negotiation.
This handles an edge case where you have a libp2p node configured with no dedicated muxer(s), instead transport(s) that incorporate their own muxers but that use Noise to exchange PeerIDs.
Splits the existing muxer negotiation test out into it's own file and adds more tests to handle the various configurations.
=> fix: support handshake-only with no muxers
